[package]
name = "cortex-m-rtic"
version = "2.0.0"
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tjäder <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std", "asynchronous"]
description = "cortex-m RTIC distribution crate"
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
rtic-app-macro = { path = "rtic-app-macro" }
riscv-slic = { version = "0.1.1" }
esp32c3 = { version = "0.26.0" }
riscv = { version = "0.12.1" }
portable-atomic = { version = "1" }
critical-section = "1"


[features]
default = []
riscv-esp32c3 = ["rtic-app-macro/riscv-esp32c3"]
riscv-riscv-slic = ["rtic-app-macro/riscv-slic"]
