[package]
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tjäder <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std", "asynchronous"]
description = "Real-Time Interrupt-driven Concurrency (RTIC): a concurrency framework for building real-time systems"
documentation = "https://rtic.rs/"
edition = "2021"
keywords = ["embedded", "async", "runtime", "no-std", "rtos"]
license = "MIT OR Apache-2.0"
name = "rtic"
readme = "../README.md"
repository = "https://github.com/rtic-rs/rtic"

version = "2.1.2"

[package.metadata.docs.rs]
features = ["thumbv7-backend"]

[lib]
name = "rtic"

[dependencies]
riscv-slic = { version = "0.1.1", optional = true } # TODO: remove after riscv-distro is ready                                                 #TODO: remove after riscv-distro is introduced
esp32c3 = { version = "0.26.0", optional = true }  # TODO: remove after riscv-distro is ready                                                  #TODO: remove after riscv-distro is introduced
riscv = { version = "0.12.1", optional = true }   # TODO: remove after riscv-distro is ready                                                   #TODO: remove after riscv-distro is introduced
bare-metal = "1.0.0"
portable-atomic = { version = "1", default-features = false }                                        #TODO: remove after riscv-distro is introduced
rtic-core = "1"
critical-section = "1"
cortex-m-rtic = { version = "2.0.0", path = "../rtic-distributions/cortex-m-rtic", optional = true }

[dev-dependencies]
lm3s6965 = "0.2"
cortex-m-semihosting = "0.5.0"

[dev-dependencies.futures]
version = "0.3.26"
default-features = false
features = ["async-await"]

[dev-dependencies.panic-semihosting]
features = ["exit"]
version = "0.6.0"

[target.x86_64-unknown-linux-gnu.dev-dependencies]
trybuild = "1"

[features]
default = []

thumbv6-backend = ["cortex-m-rtic", "cortex-m-rtic/cortex-m-source-masking"]
thumbv7-backend = ["cortex-m-rtic", "cortex-m-rtic/cortex-m-basepri"]
thumbv8base-backend = ["cortex-m-rtic", "cortex-m-rtic/cortex-m-source-masking"]
thumbv8main-backend = ["cortex-m-rtic", "cortex-m-rtic/cortex-m-basepri"]

riscv-esp32c3-backend = ["esp32c3", "riscv"]
riscv-clint-backend = ["riscv", "riscv-slic/clint-backend"]

# needed for testing
test-critical-section = ["portable-atomic/critical-section"]
