[package]
name = "cortex-m-rtic"
version = "2.0.0"
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tjäder <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std", "asynchronous"]
description = "cortex-m RTIC distribution crate"
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
rtic-app-macro = { path = "rtic-app-macro" }
critical-section = "1"


[features]
default = []
