[package]
name = "rtic-macros-ui-tests"
version = "2.0.0"
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tjäder <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std", "asynchronous"]
description = "proc-macro crate for allowing running the ui tests for validating the tokenstream parsing of rtic-macros crate"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
rtic-macros = { path = ".." }
proc-macro2 = "1.0.49"
proc-macro-error2 = "2.0"
quote = "1.0.23"
syn = { version = "2.0.48", features = ["extra-traits", "full"] }

[dev-dependencies]
trybuild = "1.0.73"
